### ISSUE TITLE
Is a writing row to a db with 2 replicas equal  3 writes?

### ISSUE THREAD

**Issue by ambrt** [tursodatabase/turso-docs#120]
Just one minor thing but how are total monthly writes calculated when there are replicas?

If i add one row to a db with 2 replicas (3 location in total) is that one write or 3?

I assume that reads are counted 1 to 1 (one request is routed to just one replica)

**Comment by MarinPostma** [comment]
Hey @ambrt! Row write are accounted for at query execution, so not matter how many replicas you have 1 row written = 1 row written accounted :)

**Comment by ambrt** [comment]
That clears it. Thank you :)
