### ISSUE TITLE
Windows CLI installation clarification

### ISSUE THREAD

**Issue by KeshiaRose** [tursodatabase/turso-docs#154]
On the [CLI Introduction page](https://docs.turso.tech/cli/introduction) for the first install step, I think it would be nice to add a comment or note for the Windows installation about needing to install WSL first. Perhaps even just a link to the full [Windows installation guide](https://docs.turso.tech/cli/installation#windows)? It took me a bit to realize I needed to do this step first since it wasn't mentioned on the introduction page.

**Comment by notrab** [comment]
Hey @KeshiaRose, that's a great idea! Do you think it would be better to combine the steps outlined [here](https://docs.turso.tech/cli/installation#windows)?

**Comment by KeshiaRose** [comment]
@notrab Maybe? Perhaps one of those accordions could be added with additional info or alternative methods? The introduction page is a nice short length though, that might be too much all in one spot.

**Comment by notrab** [comment]
I'll go ahead and close this, but happy to revisit this with a PR of a good balance. We know Windows story could be better.
