### ISSUE TITLE
WCAG: unreadable text contrast

### ISSUE THREAD

**Issue by leandergangso** [tursodatabase/turso-docs#158]
I'm pretty sure this is not WCAG compliant :)

![image](https://github.com/tursodatabase/turso-docs/assets/60340480/9887ae49-419a-41ed-8db0-2fb0a612a0e4)

**Comment by notrab** [comment]
Hey @leandergangso, we're aware of this and currently chatting with Mintlify (which powers our docs) if there is a way for us to use our branding, but customise the colours of search and "copy to clipboard" buttons.

I'll keep you updated, and thanks for the report 🙌🏻

**Comment by notrab** [comment]
Hey @leandergangso , I've reverted to using another colour until Mintlify has the option to override this specific colour setting.

Thanks for reporting 🙏🏻 

![CleanShot 2024-03-14 at 10 13 32@2x](https://github.com/tursodatabase/turso-docs/assets/950181/c95abb65-136d-4687-a533-b026e9239f89)
