### ISSUE TITLE
Css bug in Dashboard

### ISSUE THREAD

**Issue by ambrt** [tursodatabase/turso-docs#182]
I didn't find any better repo to post this bug so here it is.

I'm on rather small screen and ubuntu+firefox.
So the DB view in dashboard doesn't get  background color for overflowing content.
Its ok for for "first screen".

The right side, after horizontal scroll:
![Screenshot from 2024-04-07 20-19-44](https://github.com/tursodatabase/turso-docs/assets/10456131/b49fb6af-efd0-4aec-bd54-87901a589c81)

**Comment by notrab** [comment]
Hey, sorry for the delay! This should no longer be an issue since we refreshed the dashboard 💅🏻
