### ISSUE TITLE
I cannot log in my turso account in Gitpod.

### ISSUE THREAD

**Issue by officialrajdeepsingh** [tursodatabase/turso-docs#190]
I'm using Gitpod IDE. I'm running turso auth login command to login, after permission to turso callback API return on local host.

**Comment by notrab** [comment]
Hey, I'm not entirely familiar with the flow you're describing. Can you share more (screenshots too) about the process you're following? There's a [`--headless`](https://docs.turso.tech/cli/headless-mode) option for the CLI which might be useful here to debug.

**Comment by officialrajdeepsingh** [comment]
Yes I try it it does not work

**Comment by notrab** [comment]
I'm going to close this for now, but please report back if you have a full walkthrough of what you're doing, with any screenshots of the errors if this is still an issue.
