### ISSUE TITLE
--headless login ang signup

### ISSUE THREAD

**Issue by Aziz798** [tursodatabase/turso-docs#191]
After going to the url and getting the token ,when i paste it i got an error that i should login before i make a command 
It's funny that i have to login to login

**Comment by haaawk** [comment]
Good catch @Aziz798. Let me fix that for you real quick.

**Comment by haaawk** [comment]
Fixed in https://github.com/tursodatabase/turso-cli/pull/863
Available in turso-cli v0.93.8
