### ISSUE TITLE
Issue on docs - Drizzle + Turso

### ISSUE THREAD

**Issue by u2ix** [tursodatabase/turso-docs#194]
When I try to create the migration with the `drizzle.config.ts` on the [documentation](https://docs.turso.tech/sdk/ts/orm/drizzle), I receive an error.

I think it's not happy about `driver: "turso"` 🤷 

```
$ drizzle-kit generate


ZodError: [
  {
    "expected": "'postgresql' | 'mysql' | 'sqlite'",
    "received": "undefined",
    "code": "invalid_type",
    "path": [
      "dialect"
    ],
    "message": "Required"
  }
]
```

**Comment by u2ix** [comment]
Ok what's missing in the docs, for `drizzle.config.ts`
```
dialect: "sqlite",
```

**Comment by notrab** [comment]
@u2ix this must be a new addition to Drizzle Kit. Feel free to open a pull request, otherwise I will investigate and prepare some updated docs after next week.

Thanks for the report!
