### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by james0r** [tursodatabase/turso-docs#195]
Path: /sdk/ts/guides/nextjs

Code examples could provide file locations. 

It seems that we're creating our `client` in `@/lib/turso`? If so, why is it not exported and why are we importing a named export of `turso` when we initialized a `const client`.

**Comment by notrab** [comment]
Hey @james0r 

Thanks for opening this issue.

I've updated the examples to use `turso`, and updated the `createClient` to export `turso` now too. Thanks for that.

I'll make some further updates to the examples soon which will make the file names clearer (if applicable).

Feel free to open a PR if you see or spot anything that doesn't look right, happy to merge any requests.
