### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by IntegerAlex** [tursodatabase/turso-docs#214]
[Path:](url) /sdk/ts/examples

There are no Examples Rendered on this page,
![Screenshot 2024-07-14 185137](https://github.com/user-attachments/assets/8fa84caf-ccef-4be9-b120-d780f2b58ec7)

**Comment by notrab** [comment]
Hey, this page is a redirect. I will mention it to the team who build the docs platform to let them know. If you access `TS > Examples` from the nav, the redirect should work.

**Comment by IntegerAlex** [comment]
I got that, It feels like it will render but it didn't. fix it

**Comment by notrab** [comment]
@IntegerAlex there's nothing to fix per se, it's a redirect issue (that I c
