### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by spiderman-eth** [tursodatabase/turso-docs#215]
Path: /sdk/php/quickstart

Trouble with the documentation (probably skill issue 😆)

- curl --proto '=https' --tlsv1.2 -sSf "https://darkterminal.github.io/turso-php-installer/dist/turso-php-installer.phar"
./turso-php-installer.phar
zsh: no such file or directory: ./turso-php-installer.phar
- following the steps (Turso PHP Installer (Linux/macOS only)) – is not working for me.
- Which TURSO_DATABASE_URL= is required? (https://[db-name]/v2/pipeline)
- would be nice to add the file names where to add the code snippets

btw. not expecting to get an answer on this, but why should I choose this instead of [turso-laravel
](https://github.com/richan-fongdasen/turso-laravel)

**Comment by notrab** [comment]
Hey, I discovered the same issue yesterday. @darkterminal is looking into it, thanks for your patience.

**Comment by darkterminal** [comment]
Hi @spiderman-eth, You can now use this command:

```
curl https://darkterminal.github.io/turso-php-installer/dist/turso-php-installer.phar -o ./turso-php-installer.phar
```

I am also update the [README.md](https://github.com/darkterminal/turso-php-installer?tab=readme-ov-file#installation)

**Comment by notrab** [comment]
I'll close this but feel free to reopen if the issue arises again.
