### ISSUE TITLE
Issue on docs : powershell support

### ISSUE THREAD

**Issue by nikhil-swamix** [tursodatabase/turso-docs#219]
Path: /cli/introduction
hello, needed a powershell to compatible with CLI, WSL is not feasible. thanks and regards. python pip install turso will work? let me know,  wsl eats few GB ram.
Regards.

**Comment by notrab** [comment]
Hey @nikhil-swamix, we don't have the bandwidth currently to extend support outside WSL. If you do find it works, I'd be happy to document (with a warning) anything to the CLI installation page with your suggestions.

**Comment by nikhil-swamix** [comment]
i understand, can you give hint, where exactly the windows native limit comes (non wsl)? as i believe the database core is in C, it would compile to respective binaries. or im making wrong assumption?
