### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by aarreedd** [tursodatabase/turso-docs#224]
Path: /sdk/php/guides/laravel

I really want to use this, but install does not work and there are many issues. Does not feel production-ready.

1) `curl --proto '=https' --tlsv1.2 -sSf "https://darkterminal.github.io/turso-php-installer/dist/turso-php-installer.phar"` should be `curl --proto '=https' --tlsv1.2 -sSf "https://darkterminal.github.io/turso-php-installer/dist/turso-php-installer.phar" -O`

2) `php --m | grep libsql` should be `php -m | grep libsql`

3) After running `turso-php-installer install` it says "Turso Client is Ready!". Then I run `php -m | grep libsql` and libsql is not installed :(

4) The install script should be non-interactive. Currently that is not possible.

**Comment by notrab** [comment]
@darkterminal are you able to help out here and see what's going on?

**Comment by darkterminal** [comment]
I will work for that... thank you for reporting this issue...
