### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by philippviereck** [tursodatabase/turso-docs#246]
Path: /api-reference/databases/invalidate-tokens

Code snippet is wrong

```
import { createClient } from "@tursodatabase/api";

const turso = createClient({
  org: "...",
  token: "",
});

const response = await turso.databases.invalidateTokens("my-db");
```

@tursodatabase/api does not use `turso.databases.invalidateTokens("my-db");` but rather `turso.databases.rotateTokens("my-db");`

**Comment by notrab** [comment]
Thanks @philippviereck , I've updated this 😍
