### ISSUE TITLE
Document that Vercel edge functions require `https:`

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso-docs#25]
Vercel edge functions don't seem to support WebSockets as per https://github.com/libsql/libsql-client-ts/issues/23. We need to fix the error message, of course, but let's also mention somewhere in the docs that edge functions require `https:`.

**Comment by CodingDoug** [comment]
We already have documentation that states https is required where websockets are not available.  In what way could this be improved? https://docs.turso.tech/reference/libsql-urls

**Comment by penberg** [comment]
We should probably have a table of the common ones: Vercel, Netlify, Cloudflare, etc., and explicitly mention what they support.

**Comment by CodingDoug** [comment]
OK, let's compile that data here and I'll figure out a good way to present it.

**Comment by penberg** [comment]
@honzasp Do you have any additional information?

**Comment by honzasp** [comment]
- Vercel edge functions: HTTP only, version 0.1.3 of `@libsql/client` now throws a nice error message when the user attempts to use WebSocket.
- Netlify edge functions: both HTTP and WebSockets (with version 0.1.3 of `@libsql/isomorphic-ws` to fix an import issue). The client can be imported from `"https://esm.sh/@libsql/client@0.1.3"`. Standalone Deno also accepts npm imports `"npm:@libsql/client@0.1.3"`, but this does not yet work on Netlify for some reason.
