### ISSUE TITLE
Document piping to `turso db shell`

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso-docs#60]
You can pipe SQL commands to the shell with:

```console
echo "SELECT 1;" | turso db shell endless-odin
```

Let's document that for discoverability.

**Comment by CodingDoug** [comment]
The fact that you can do this doesn't really mean that someone *should* do this.  The problem right now is that the handling of input and output is a bit of a mess right now from the perspective of someone trying to send SQL non-interactively via stdin.  What the CLI needs to do is:

- Detect when it's invoked non-interactively (not having a TTY)
- Suppress all normal output (welcome message, prompts, tabular output)
- Define what the output *should* be given that input could be anything (maybe a parseable summary of what happened in total?)
- Define what happens in the event of a SQL error (stop? keep processing input?)
- Define useful exit codes
